name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: exit 1
      name: Fail
      id: should_release
      continue-on-error: true
    - run: |
        echo "No release required. Exiting..."
        exit 0
      if: steps.should_release.outcome != 'success'
    - run: echo "should be skipped"
